
import React from 'react';
import { ActionItem } from '../types';

interface ActionItemsPanelProps {
  isOpen: boolean;
  onClose: () => void;
  items: ActionItem[];
  isLoading: boolean;
  onRefresh: () => void;
}

export const ActionItemsPanel: React.FC<ActionItemsPanelProps> = ({ isOpen, onClose, items, isLoading, onRefresh }) => {
  return (
    <>
      {/* Backdrop */}
      <div 
        className={`fixed inset-0 bg-black/60 backdrop-blur-sm z-[60] transition-opacity duration-300 ${isOpen ? 'opacity-100' : 'opacity-0 pointer-events-none'}`}
        onClick={onClose}
      />
      
      {/* Sidebar */}
      <div className={`fixed right-0 top-0 h-full w-full max-w-sm glass-card border-l border-white/10 z-[70] shadow-2xl transition-transform duration-500 ease-out ${isOpen ? 'translate-x-0' : 'translate-x-full'}`}>
        <div className="flex flex-col h-full">
          <div className="p-6 border-b border-white/5 flex items-center justify-between">
            <div>
              <h2 className="text-xl font-bold text-white flex items-center">
                <i className="fas fa-clipboard-check text-indigo-400 mr-3"></i>
                Action recap
              </h2>
              <p className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mt-1">Smart Extraction</p>
            </div>
            <button onClick={onClose} className="h-10 w-10 flex items-center justify-center rounded-full hover:bg-slate-800 text-slate-400 transition-colors">
              <i className="fas fa-times"></i>
            </button>
          </div>

          <div className="flex-grow overflow-y-auto p-6 space-y-4">
            {isLoading ? (
              <div className="flex flex-col items-center justify-center h-40 space-y-4 text-slate-400">
                <i className="fas fa-circle-notch fa-spin text-2xl text-indigo-500"></i>
                <p className="text-sm font-medium animate-pulse">Analyzing conversation history...</p>
              </div>
            ) : items.length === 0 ? (
              <div className="text-center py-12 px-4">
                <div className="h-16 w-16 bg-slate-900 rounded-full flex items-center justify-center mx-auto mb-4 border border-slate-800">
                  <i className="fas fa-ghost text-slate-700 text-2xl"></i>
                </div>
                <h3 className="text-slate-300 font-semibold mb-1">No tasks detected</h3>
                <p className="text-slate-500 text-xs">I couldn't find any specific action items in your conversation yet.</p>
              </div>
            ) : (
              items.map((item, idx) => (
                <div key={idx} className="bg-slate-900/40 border border-white/5 rounded-2xl p-4 hover:border-indigo-500/30 transition-all group">
                  <div className="flex items-start justify-between mb-2">
                    <span className={`text-[9px] font-black uppercase tracking-widest px-2 py-0.5 rounded-full border ${
                      item.priority === 'high' ? 'bg-red-500/10 text-red-400 border-red-500/20' :
                      item.priority === 'medium' ? 'bg-orange-500/10 text-orange-400 border-orange-500/20' :
                      'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'
                    }`}>
                      {item.priority}
                    </span>
                  </div>
                  <p className="text-sm text-slate-200 font-medium leading-relaxed group-hover:text-white transition-colors">{item.task}</p>
                  {item.context && (
                    <p className="text-[11px] text-slate-500 mt-2 italic leading-snug">"{item.context}"</p>
                  )}
                </div>
              ))
            )}
          </div>

          <div className="p-6 border-t border-white/5 bg-slate-950/50">
            <button 
              onClick={onRefresh}
              disabled={isLoading}
              className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-800 text-white font-bold py-3 px-4 rounded-xl flex items-center justify-center transition-all active:scale-[0.98]"
            >
              {isLoading ? (
                <i className="fas fa-circle-notch fa-spin mr-2"></i>
              ) : (
                <i className="fas fa-sync-alt mr-2"></i>
              )}
              Re-scan History
            </button>
            <p className="text-center text-[10px] text-slate-600 mt-4 px-2">
              Action items are generated by AI. Always verify critical tasks manually.
            </p>
          </div>
        </div>
      </div>
    </>
  );
};
